
services:
  mariadb:
    image: mariadb:10.11
    container_name: travel-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: travel_planner
      MYSQL_USER: travel_user
      MYSQL_PASSWORD: travel_password
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - travel-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: travel-backend
    environment:
      NODE_ENV: production
      PORT: 5001
      DB_HOST: mariadb
      DB_USER: travel_user
      DB_PASSWORD: travel_password
      DB_NAME: travel_planner
      JWT_SECRET: travel-planner-secret-key
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5001:5001"
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - travel-network
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: travel-frontend
    environment:
      VITE_API_URL: http://localhost:5001/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - travel-network

volumes:
  mariadb_data:

networks:
  travel-network:
    driver: bridge