services:
  cherry-blossom-app:
    build: .
    ports:
      - "5002:5002"
    volumes:
      - ./uploads:/app/uploads
      - ./wedding.db:/app/wedding.db
    environment:
      - NODE_ENV=production
      - PORT=5002
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/api/wedding-info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s